### ISSUE TITLE
Alert detection and insertion system

### ISSUE THREAD

**Issue by martinjohndyer** [GOTO-OBS/gtecs-control#328]
_There were about 3 or 4 different places I could put this plan, but in the end I decided to put it here. Because it's ultimately a control system issue, and because I like to keep things organised on here if I can._

OK, here's my initial implementation plan for the alerts system for GOTO. See https://github.com/GOTO-OBS/goto/wiki/Alert-response for what we want to do, this is, in my opinion, how we want to do it.

For reference there are three key modules, aside from G-TeCS:
* [goto-alert](https://github.com/GOTO-OBS/goto-alert), to deal with listening and parsing alerts,
* [goto-tile](https://github.com/GOTO-OBS/goto-tile), to process events that cover more than a single pointing, and
* [goto-obsdb](https://github.com/GOTO-OBS/goto-obsdb), to insert events into the observing database to be picked up by the scheduler

### Level 1 - the sentinel daemon (G-TeCS)

This will be a G-TeCS daemon like all the others, running on the database server in SuperWASP alongside the database itself and the separate scheduler daemon.

It should have two threads:
- A control thread like the other daemons, so it can be started and stopped and we can add other commands (ideas - pause/resume the alerts listener, info could return details on the latest alert inserted and statistics).
- An alert listener thread. As I see it this would contain logic duplicating Leo Singer's [PyGCN](https://github.com/lpsinger/pygcn) module's way of listening VOEvents (see [voeventclient.py](https://github.com/lpsinger/pygcn/blob/master/gcn/voeventclient.py)). I much prefer this to messing about with [Comet](https://comet.readthedocs.io/en/stable/index.html) and Twisted and so on, you just open a socket and listen in. For reference pt5m has its own implementation directly using Twisted, but I like the PyGCN way of doing it. In the grand scheme it doesn't make a huge amount of difference though, however we do it this is where we should be listening for new VOEvents.

### Level 2 - handling events (GOTO-alert)

Whenever an alert comes in we want to pass it to a handler function which should be the job of GOTO-alert. As far as G-TeCS is concerned we should just be able to do `from gotoalert import handle_voevent`, or whatever it's called, and feed any new events into that.

Here's an incomplete list of things we want the handler to do, most of which is already done within [GOTO-alert's alert.py](https://github.com/GOTO-OBS/goto-alert/blob/master/alert.py):

* Parse the event using Tim Staley's [voevent-parse](https://github.com/timstaley/voevent-parse) to load in the XML.
* Work out what sort of event it is (at a very basic level, e.g. it's from Swift or Fermi or LIGO or Icecube...).
* Filter by viability. Now this might be the tricky part, because most of the actual observing decisions should be made by the scheduler later when it's picking it out of the database. I mean things like current altitude, distance from the Moon etc. Those are things that need to be recalculated each time the scheduler runs, and furthermore once we have multiple sites they will be evaluated by the schedulers at each location. However I do think there should still be some filtering at this stage - for example if it's currently behind the Sun and won't be visible for 6 months then it's probably not worth submitting. Or maybe it's too close to the galactic centre, or it's a really faint source that we'll almost certainly never detect (I don't know how we'd determine that, but it's an example). Or maybe there's some false alarm threshold we want to set that will reject poor candidates (we could do that for GW events, but I don't think we'll want to).
* If we know it's something we're interested in then we can send out Slack alerts/emails etc. In fact we probably want to do that even if we aren't, something like "GRBXXXXX detected, but will not be visible from GOTO within the next XX days."
* Finally we want to insert the event into the database. This should be done using a function from the ObsDB module which just takes the key information - name, coordinates, a skymap if there is one (we should come up with a nice class or way to contain the data).

### Level 3 - inserting into the database (ObsDB and GOTO-tile)

This should once again be a simple function that is imported by GOTO-alert, and inserting the event into the database shouldn't be too difficult. We already have several scripts that can do this, including `add_pointing` and [`skymap2db`](https://github.com/GOTO-OBS/goto-obsdb/blob/master/obsdb/scripts/skymap2db) which I explicitly wrote to do what I anticipated we'd need to do for a LIGO alert.

In my opinion exactly what we want to insert into the database (number of exposures, filters etc...) for each type of alert should be defined here in the ObsDB module. Likewise it should be here that we run GOTO-tile's griddling function (currently called `tile_skymap`) to split any large areas up into pointings and insert each of them, with the associated probability rankings.

We should also populate the `Events` table within the database, which will mean each image will have cards for the event ID, name, IVON etc making them easy to group together.

### Summary

```
Sentinel daemon (G-TeCS)
When an event comes in...
     ||
     \/
handle_event() (GOTO-alert)
If we can/want to observe it...
     ||
     \/
insert_event() (ObsDB)
If it takes multiple pointings...
     ||
     \/
tile_skymap() (GOTO-tile)
```

I think this is a reasonable plan of action, which will integrate Alex's work in GOTO-alert. I tried to keep things split into fairly logical divisions - G-TeCS shouldn't need to worry about exactly what an event is just hand it off to GOTO-alert. Likewise GOTO-alert shouldn't need to know anything about the database structure or the tiling, that's all handled within ObsDB/GOTO-tile.

I'm open to suggestions, and we can discuss it here, on Slack and at the telecons. Especially @alexobrads of course, @outs1der, @dsteeghs and anyone else interested. Note this is just the basic framework to get started, there is plenty more we can add on top of it for more advanced response and feedback.

### Todo

If we decide this is the way to go, here's a quick list of things to get started. We can raise issues for the ones that don't have them after we've discussed the plan.

- [x] Start work on a framework sentinel daemon within in G-TeCS using the PyGCN system  (#309)
- [x] Make GOTO-alerts into a Python module
- [x] Make a handler function within GOTO-alert which the daemon can import and pass in the raw XML
- [x] Make an insertion function within ObsDB which the GOTO-alert handler can import and pass in the event to be inserted
- [x] Create an events module in ObsDB which can contain the observing details for each type of event
- [x] (Eventually) Look into expanding GOTO-tile to deal with non-LIGO sources (eg Fermi) (GOTO-OBS/goto-tile#47)
